name = "Seance3"
version = "0.1.0"
defaultTargets = ["seance3"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4.git"
rev = "v4.33.1"

[[lean_lib]]
name = "Seance3"

[[lean_exe]]
name = "seance3"
root = "Main"
